# xbacklight
# Autogenerated from man page /usr/share/man/man1/xbacklight.1.gz
complete -c xbacklight -s h -o help -d 'Print out a summary of the usage and exit'
complete -c xbacklight -o time -d 'Length of time to spend fading the backlight between old and new value'
complete -c xbacklight -o steps -d 'Number of fading steps'
complete -c xbacklight -o fps -d 'Target frame rate (frames/steps per second)'
complete -c xbacklight -o display -d 'Ignored for backward compatibility'
complete -c xbacklight -o ctrl -d 'Set the device name to operate on'
complete -c xbacklight -o list -d 'Print the list of controllable devices'
complete -c xbacklight -o get -d 'Print out the backlight brightness as a percentage'
complete -c xbacklight -o getf -d 'Same as -get, but without rounding'
complete -c xbacklight -o get-steps -d 'Return the number of available brightness steps'
complete -c xbacklight -o set -d 'Sets the backlight brightness to the specified percentage level'
complete -c xbacklight -o inc -d 'Increases brightness by the specified amount'
complete -c xbacklight -o dec -d 'Decreases brightness by the specified amount'
complete -c xbacklight -o perceived -d 'Adjust the display according to the perceived brighness instead of operating …'

